---

- hosts: server1
  gather_facts: no
  become: yes
  tasks:
    - name: Modify file content
      lineinfile:
        dest: "/home/boris3/testFile"
        regexp: "key2="
        line: "key2=this line is modified "
        state: present

