---
- hosts: server1
  become: yes
  tasks:
      - name: clone github repo
        git:
          repo: https://github.com/BorisRadenkovic/Jenkins-shared-library.git
          dest: /home/boris3/clone_repo