---

- hosts: server1
  become: yes
  tasks:
    - name: Create Directory
      file:
        path: "/home/boris3/{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - TEST1
        - TEST2
        - TEST3
