---
- hosts: server1
  become: yes
  vars:
    - warName: webgoat-server-v8.1.0.war
    - warRemotePath: /var/lib/tomcat9/webapps/ROOT
  tasks:
    - name: Create WAR file
      shell: "jar -cvf/home/boris3/webgoat-server-v8.1.0.war *"

    - name: Download WAR to server
      synchronize: src={{ /home/boris3/ }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}

    - name: Unzip WAR file
      unarchive: src={{ warRemotePath }}/{{ warName }} dest=/var/lib/tomcat9/webapps/ROOT copy=no mode=0755 owner=tomcat9 group=tomcat9
      notify:
        - Restart tomcat9

    - name: Delete remote war file
      file: path={{ warRemotePath }}/{{ warName }} state=absent

  handlers:
    - name: Restart tomcat9
      service: name=tomcat9 state=restarted
